---
- name: Inlcude zsh variables for specific OS
  ansible.builtin.include_vars: "{{ lookup('first_found', zsh_os_variable_files) }}"
  tags:
    - zsh
    - zinit

- name: Install zsh
  ansible.builtin.import_tasks: "install_zsh.yml"
  tags:
    - zsh
    - zinit

- name: Configure templates
  ansible.builtin.import_tasks: templates.yml
  tags:
    - zsh
    - zsh-templates
  when: zsh_install_templates

- name: Install zinit
  ansible.builtin.import_tasks: zinit.yml
  tags:
    - zsh
    - zinit
  when: zsh_install_zinit
