---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    force: false
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ${MOLECULE_DISTRIBUTION:-debian10}
    image: "nekeal/${MOLECULE_DISTRO:-debian10}-ansible-systemd:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
